name: CD 

on:
  workflow_call:

jobs:
  deploy:
    # deploy on self-hosted runner
    runs-on: self-hosted
    steps:
      - name: Code checkout
        uses: actions/checkout@v7

      - name: Docker setup [Login]
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: deploy the container with Docker compose
        run: |
          docker compose pull
          docker compose up -d        


